fledge-iot/fledge-service-notification

C/services/common/delivery_queue.cpp
Added missing running flag check in DeliveryQueue::process
=> FOGL-4640: Notification server shutdown does not complete

C/services/common/notification_manager.cpp
=> FOGL-4747: compilation fix

C/services/common/notification_manager.cpp, C/services/common/threshold_rule.cpp
Make use of SP_BUILTIN parameter
=> Make use of SP_BUILTIN parameter

C/services/notification/CMakeLists.txt
FOGL-3212: create needed foldersCreate needed folders
=> FOGL-3212: create needed folders

C/services/common/notification_queue.cpp
Signed-off-by: Mark Riddoch <mark@dianomic.com>
=> FOGL-5828 Add ability to send data to notification delivery plugins

C/services/common/include/notification_manager.h, C/services/common/include/notification_queue.h, C/services/common/notification_manager.cpp, C/services/common/notification_queue.cpp, C/services/common/notification_subscription.cpp
FOGL-6036: Time based rule implementation
=> FOGL-6036: Time based rule implementation

C/services/common/include/notification_manager.h, C/services/common/notification_manager.cpp, C/services/common/notification_queue.cpp, C/services/common/notification_subscription.cpp
FOGL-6037: implementation of multiple assets evaluation option
=> FOGL-6037: implementation of multiple assets evaluation option

C/services/common/notification_queue.cpp
FOGL-6036: fix for timestamp string conversion
=> FOGL-6036: fix for timestamp string conversion

C/services/common/include/notification_queue.h, C/services/common/notification_queue.cpp
FOGL-6036: process data buffers only when evaluating time based rule
=> FOGL-6036: process data buffers only when evaluating time based rule

C/services/common/notification_queue.cpp
FOGL-6036: dynamically set thread sleep time for time based rules
=> FOGL-6036: dynamically set thread sleep time for time based rules

C/services/common/include/notification_service.h, C/services/common/notification_service.cpp, C/services/notification/notification.cpp
FOGL-5144: pass startup token in service registration
=> FOGL-5144: pass startup token in service registration

C/services/common/include/notification_service.h, C/services/common/notification_service.cpp, C/services/notification/notification.cpp
FOGL-6189: Fix startup log messages
=> FOGL-6189: Fix startup log messages

C/services/common/include/notification_service.h
FOGL-5144: addition of isRunning() routine
=> FOGL-5144: addition of isRunning() routine

C/services/common/include/notification_service.h
FOGL-6100: needed changes before merging core branch
=> FOGL-6100: needed changes before merging core branch

C/services/common/notification_service.cpp
=> FOGL-6056: Compilation fix

C/services/common/include/notification_service.h, C/services/common/notification_service.cpp, C/services/notification/notification.cpp
The allows the service to create configuration without needing to be run
=> FOGL-5181 Add --dryrun flag

C/services/common/notification_service.cpp
Signed-off-by: ashish-jabble <ashish@dianomic.com>
=> FOGL-6689 Fixes made for no matching function call in createSecurityCategories

C/services/common/notification_service.cpp
FOGL-6611: addition of SERVICE_TYPE
=> FOGL-6611: addition of SERVICE_TYPE

C/services/common/data_availability_rule.cpp, C/services/common/include/data_availability_rule.h, C/services/common/include/notification_subscription.h, C/services/common/notification_manager.cpp, C/services/common/notification_subscription.cpp
Signed-off-by: nandan <nandan.ghildiyal@gmail.com>
=> FOGL-7250: Create DataAvailability rule

C/services/notification/include/notification_api.h, C/services/notification/include/notification_subscription.h, C/services/notification/include/threshold_rule.h, C/services/notification/notification_api.cpp, C/services/notification/notification_manager.cpp, C/services/notification/notification_subscription.cpp, C/services/notification/threshold_rule.cpp
subscriptions
Signed-off-by: Mark Riddoch <mark@dianomic.com>
=> FOGL-7433 Add support for statistics and statisticRate notification

C/services/notification/notification_service.cpp
Signed-off-by: Mark Riddoch <mark@dianomic.com>
Requires FOGL-7421 before merging
=> FOGL-7425 Add AuditLogger singleton.

C/services/notification/include/notification_api.h, C/services/notification/include/notification_manager.h, C/services/notification/include/notification_queue.h, C/services/notification/include/notification_subscription.h, C/services/notification/notification_api.cpp, C/services/notification/notification_manager.cpp, C/services/notification/notification_queue.cpp, C/services/notification/notification_service.cpp, C/services/notification/notification_subscription.cpp
=> FOGL-7469 Register and unregister reworked to always make the right call

C/services/notification/notification_queue.cpp
FOGL-7467: skip empty datapoint values
=> FOGL-7467: skip empty datapoint values

C/services/notification/notification_subscription.cpp
=> FOGL-7539: fix variable name

C/services/notification/include/notification_manager.h, C/services/notification/notification_manager.cpp, tests/unit/C/services/notification/check_notification_state.cpp
FOGL-9076: retrigger_time is now a float, with minimum value of 0.1 seconds
=> FOGL-9076: retrigger_time is now a float, with minimum value of 0.0 seconds
